---
title: VISTAS - Visualising Industry Skill TAlent Shifts
author:
  - name: Cheryl Pay Wei Lin
    email: cheryl.pay.2019@mitb.smu.edu.sg
    affiliation: Singapore Management University
  - name: Chong Jia Jun Louis
    email: louis.chong.2019@mitb.smu.edu.sg
    affiliation: Singapore Management University
  - name: Lau Wei Han Amos
    email: amos.lau.2019@mitb.smu.edu.sg
    affiliation: Singapore Management University
abstract: |
  [write abstract for research paper such as data viz methods, evals, user interface design] VISTAS - Visualising Industry Skill TAlent Shifts is a shiny app that aims to provide insights to talent, migration and skill trends in an interactive and user-friendly way... (no more than 300 words)
bibliography: sigproc.bib
csl: acm-sig-proceedings.csl
output: rticles::acm_article
---


# Abstract
Numerous studies have been conducted to analyse the impact of employment growth and migration on GDP per capita. However, these studies usually use datasets aggregated at country level. More can be done to deep dive into the relationship between GDP per capita, employment growth and migration within each industry to help individuals and countries better understand the rapidly evolving labour market and its impact on country’s economic growth. LinkedIn and World Bank Group have partnered to release a useful set of data from 2015 to 2019 on the employment growth and migration for different industries and skills in various countries. Together with GDP per capita data for each country, countries can study the impact of employment growth and migration for each industry and skill on GDP per capita, find out which are the key skills and whether they have been gained or lost to other countries. At the same time, individuals can analyse the labour market, identify the highly sought-after skills and countries that hold better employment opportunities for each skill. This boosts the competitive edge of countries and individuals in the labour market. To aid individuals and countries in the study, we have designed and developed VISTAS (Visualising Industry Skill TAlent Shifts), an interactive and user-friendly visual analytics dashboard.

# Introduction 
The LinkedIn and World Bank Group have partnered and released data from 2015 to 2019 that focuses on 100+ countries with at least 100,000 LinkedIn members each, distributed across 148 industries and 50,000 skill categories. This data aims to help government and researchers understand rapidly evolving labor markets with detailed and dynamic data.

Aside from being able to download the data in csv format, the visualizations at https://linkedindata.worldbank.org/data are limited in their variety and interactivity because the only allow one parameter of choice. VISTA aims to be more dynamic and interactive as a visual analytics dashboard created as a shiny app. Visualizations that have been created are scatterplots, slope graphs, treemap and more.

Explain aim of VISTA, dynamic, interactive visual analytics dashboard

This paper reports on ...
Section 1 (introduction), Section 2 (motivation/objectives), Section 3 (review of analytical techniques), Section 4 (user interface design), Section 5 (application), Section 6 (insights), Section 7 (conclusion)

# Motivation and Objectives
Through VISTA, we want to provide individuals and countries with insights into various interest areas to benchmark themselves against the global landscape. As an extension, we will be including macroeconomic indicators of GDP growth from World Bank Organization to our data visualisations. We envision that our project will help individual and countries answer questions on employability, employment opportunities, and migration and skill trends.

Instead of highlighting observations and presenting them directly, we want to enable our users to discover the insights themselves. Hence our objective is to create a simple tool for users to analyze the data in various ways, including conducting statistical analyses of regression and correlation. To do so we have added macroeconomic data from World Bank to our dashboard.  

The dashboard gives the user flexibility in selecting their own variables for every visualization. One can choose the values they want to see on their visualization, down to the x and y variables, and the categorization e.g. color by region.

# Analytical Techniques

*Limitations of existing visualizations*

Simple data visualisations are publicly available at <https://linkedindata.worldbank.org/data>. But interactivity is limited. Information is presented in one default way with no other option and the user cannot conduct comparisons "at one glance". 

Only one country is selected.
<insert screenshot showing "Pick A Country">

The map shows country migration when migration data for industry and skills are also available. Aside from a point map, the output of migration data can also be a choropleth map or slope graph.
<insert screenshot>

Studies on macroeconomic data are usually done at country level and there are limited studies to analyse the relationship between GDP per capita growth rate and employment growth or migration in each industry. These analyses are also shown as static charts in reports, lacking interactivity.

Figure 1 shows the relationship between employment growth and interstate migration (Tunny, G., 2015). Here, analysis is done at state level, but not industry level.
<insert Louis assignment Figure 1>

Figure 2 shows the relationship between GDP per capita and share of employment in business services in 2000 for countries in Europe Kox, H. & Rubalcaba, L., 2007. However, this does not show how a change in migration or employment growth in an industry will cause the change in GDP per capita.
<insert Louis assignment Figure 2>

##Statistical Analyses

## Talent Migration
The available visualisation only shows top 10 countries on the map, and top 5 countries, industries and skills in the table. A user may want to know more than just the top N for these metrics.
The visualisation of the map and table makes it difficult to visualise the inflow vs outflow of the selected country. A visualisation which allows for comparison between inflow and outflow could be useful to know if a country is gaining or losing talent.

## Industry Skills Needs
The interactive visualisation in **Industry Skills Needs panel** allows users to pick an industry group and industry, but only the skills valued in Year 2019 are shown. No option to change the year is provided.

One is hence unable to see the change in skills over the years in an industry. By presenting the changes over the years, the user is able to review trends and gather insights to the industry skills shift and sought-after skills in a particular industry.

<insert online visualisation here>

Describe analytical techniques used and explain how they can help achieve objectives

Scatter plot: Visualise values of two variables i.e. GDP per capita growth, industry employment growth, industry migration, skill migration
Regression plot: Find out relationship between two variables, how much industry employment growth, industry and skill migration impact GDP per capita growth, to what extent does industry employment growth change with industry and skill migration
Correlation matrix: Find out strength of relationship between each pair of variables, 

# User Interface Design
Explain each component of VISTA and how the combination of components will provide users certain insights

- create tabs for various topics (compartmentalization)
- ensuring positioning is not compromised with reduced window size / visualisations are not distorted when window width is reduced
- action buttons are added to delay reactions and minimize lag - eventReactive()


# Application
List and explain the packages used to create VISTA

# Insights
What has the audience learned from your work? What new insights or practices has your system enabled? A full blown user study is not expected, but informal observations of use that help evaluate your system are encouraged.

# Conclusion
Future work - ....

# Acknowledgement
Prof Kam

# References

---
references:
- id: meier2012
  title: Professinal Android 4 Application Development
  author: 
  - family: Meier
    given: Reto
  type: book
  publisher: John Wiley & Sons, Inc.
  issued:
    year: 2012
    month: 5
- id: fenner2012a
  title: One-click science marketing
  author:
  - family: Fenner
    given: Martin
  container-title: Nature Materials
  volume: 11
  URL: 'https://doi.org/10.1038/nmat3283'
  DOI: 10.1038/nmat3283
  issue: 4
  publisher: Nature Publishing Group
  page: 261-263
  type: article-journal
  issued:
    year: 2012
    month: 3
...

