---
title: "VISTAS Blog"
author: "put author here"
date: "insert date here"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Proposal

This post https://va.moomookau.org/posts/2021-02-21-visual-analytics-project-proposal/ contains the proposal for VISTAS - Visualising Industry Skill TAlent Shifts.

In the post, you can find the background, project motivation and earlier sketches of our project. The final shiny dashboard differs as we explored more R packages with greater interactivity and added them into our app to create a user-friendly analytical tool.

## Poster

Our poster, created in R Markdown is available at https://github.com/moomookau/VISTAS/blob/main/Poster/Poster.pdf.

The poster shows all the visualisation types we have in our app and includes Singapore as a Case Study to showcase insights that can be gathered by using VISTAS.

## Research Paper

The research report available for download here covers an in-depth introduction to the system architecture of our app and the limitations of certain packages that we have used. Insights for our case study on Singapore are also discussed.

## Application

VISTAS is available at https://moomookau.shinyapps.io/VISTAS/ for you to explore.